[[buildkite-agent]]
arch = "x86_64"
git-tree-sha1 = "a1bc19e7e9a28067cf4edb69a1aa452ae3f5cffb"
os = "macos"

    [[buildkite-agent.download]]
    sha256 = "e7143e58cb018634061f0a1be1d2ce80c8419bb03b0205adbb04d3a50c02f926"
    url = "https://github.com/buildkite/agent/releases/download/v3.64.0/buildkite-agent-darwin-amd64-3.64.0.tar.gz"
[[buildkite-agent]]
arch = "aarch64"
git-tree-sha1 = "004831abae1aad858e526628d9ffb7a9a442cd39"
os = "macos"

    [[buildkite-agent.download]]
    sha256 = "dc03ca90db0c626b1e0e2fe6a3fd00594f893f7bebb8867fd181476b3cabc9a8"
    url = "https://github.com/buildkite/agent/releases/download/v3.64.0/buildkite-agent-darwin-arm64-3.64.0.tar.gz"

[[buildkite-agent-rootfs]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3365eeaf1a50c423816d94cbc49a3eb34d568138"
libc = "glibc"
os = "linux"

    [[buildkite-agent-rootfs.download]]
    sha256 = "9d4978aa737ae3143e18cb036afbb341d2166291fece91dd89ee549fd6887711"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v7.0/agent_linux.armv7l.tar.gz"
[[buildkite-agent-rootfs]]
arch = "powerpc64le"
git-tree-sha1 = "bb6d9eb2a04224e57217380c24bce49b94e33d95"
libc = "glibc"
os = "linux"

    [[buildkite-agent-rootfs.download]]
    sha256 = "c4308e773df2c8ad95654cad322eda2588cf02b14ac059fc475d7d4b4310ef09"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v7.0/agent_linux.ppc64le.tar.gz"
[[buildkite-agent-rootfs]]
arch = "x86_64"
git-tree-sha1 = "90872c2338977848aac9857712a4009c14055153"
libc = "glibc"
os = "linux"

    [[buildkite-agent-rootfs.download]]
    sha256 = "d652455b98ff88d3172f21fa6280f09eb1454a8b6e14306de0f487e85bdbe74f"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v7.0/agent_linux.x86_64.tar.gz"
[[buildkite-agent-rootfs]]
arch = "aarch64"
git-tree-sha1 = "1b9f323d8d23ba3625976bc04828d4de730b86ef"
libc = "glibc"
os = "linux"

    [[buildkite-agent-rootfs.download]]
    sha256 = "669061d033cc1b8d4a49281c731abbe15e1aaa8990cc716d185cd8f99b79810c"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v7.0/agent_linux.aarch64.tar.gz"

[[docker]]
arch = "x86_64"
git-tree-sha1 = "b4df8f522b707a6bc56dc11c07c0a1d1b8703ac3"
lazy = true
libc = "glibc"
os = "linux"

    [[docker.download]]
    sha256 = "dd6ff72df1edfd61ae55feaa4aadb88634161f0aa06dbaaf291d1be594099ff3"
    url = "https://download.docker.com/linux/static/stable/x86_64/docker-20.10.11.tgz"
[[docker]]
arch = "aarch64"
git-tree-sha1 = "a4e4e60ef7942cdb26487a05bd6800be98bf1c61"
lazy = true
libc = "glibc"
os = "linux"

    [[docker.download]]
    sha256 = "87a4219c54552797ffd38790b72832372a90eceb7c8e451c36a682093d57dae6"
    url = "https://download.docker.com/linux/static/stable/aarch64/docker-20.10.11.tgz"

[[docker-rootless-extras]]
arch = "x86_64"
git-tree-sha1 = "f544afd3702e23df0819a378c6bdb2bbf6f6b828"
lazy = true
libc = "glibc"
os = "linux"

    [[docker-rootless-extras.download]]
    sha256 = "595f3bcd61aaa01ece8f967e4f6c5cd1fe05c3de9736bf595b0a7c99ba7b9eaf"
    url = "https://download.docker.com/linux/static/stable/x86_64/docker-rootless-extras-20.10.11.tgz"
[[docker-rootless-extras]]
arch = "aarch64"
git-tree-sha1 = "0320f85d281583e7f48e5b5a550ceaab287c4c5d"
lazy = true
libc = "glibc"
os = "linux"

    [[docker-rootless-extras.download]]
    sha256 = "753d79fe76fa3dedbba7d49fad48e2b9cb222b38c72d2b2040a36bff006ea9e7"
    url = "https://download.docker.com/linux/static/stable/aarch64/docker-rootless-extras-20.10.11.tgz"
