[[buildkite-agent]]
arch = "x86_64"
git-tree-sha1 = "3b6de2308d08504a747501476d2ff0f176974d8b"
os = "macos"

    [[buildkite-agent.download]]
    sha256 = "001b2784c01bfbcd58d4c8901c9ea891c42f267f563be0f53aae80a2e08c0164"
    url = "https://github.com/buildkite/agent/releases/download/v3.82.1/buildkite-agent-darwin-amd64-3.82.1.tar.gz"
[[buildkite-agent]]
arch = "aarch64"
git-tree-sha1 = "25c7c1f47a079274ee5643ea78455dcb84a41cb2"
os = "macos"

    [[buildkite-agent.download]]
    sha256 = "13291257ef355e734043d138cef66c6844a46c65da4f53ebf8e9cd59c3d8b7d6"
    url = "https://github.com/buildkite/agent/releases/download/v3.82.1/buildkite-agent-darwin-arm64-3.82.1.tar.gz"

[[buildkite-agent-rootfs]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "afca597f51805284e516d46170ff0d157f21a87d"
libc = "glibc"
os = "linux"

    [[buildkite-agent-rootfs.download]]
    sha256 = "5d13d7cc42367e1de4d5031aeff11379e097ff2531011225aec5dbb4a91c45f7"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v7.10/agent_linux.armv7l.tar.gz"
[[buildkite-agent-rootfs]]
arch = "powerpc64le"
git-tree-sha1 = "ebbbf1272ad6b7d6cd6b113663dd4f2b8c88d251"
libc = "glibc"
os = "linux"

    [[buildkite-agent-rootfs.download]]
    sha256 = "760e4ac0befeae2d74ba5d184c978ec49a7642ce38a48face58ad0cfd278c2b0"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v7.10/agent_linux.ppc64le.tar.gz"
[[buildkite-agent-rootfs]]
arch = "x86_64"
git-tree-sha1 = "5b495b8e3275e95d24d0eb4fdeedafa43c3f024f"
libc = "glibc"
os = "linux"

    [[buildkite-agent-rootfs.download]]
    sha256 = "4101d4c1e25bbc0fc4d56d2c49ac2fe16c8129c7f9742d098d3644a8e6f1bcb6"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v7.10/agent_linux.x86_64.tar.gz"
[[buildkite-agent-rootfs]]
arch = "aarch64"
git-tree-sha1 = "7ea7bee841f0ce896d8cc04218b27e376901899b"
libc = "glibc"
os = "linux"

    [[buildkite-agent-rootfs.download]]
    sha256 = "3de49747e85abd9c8198bf2c399acdd966a9675b952582d098b9477e7af3b3b0"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v7.10/agent_linux.aarch64.tar.gz"

[[docker]]
arch = "x86_64"
git-tree-sha1 = "b4df8f522b707a6bc56dc11c07c0a1d1b8703ac3"
lazy = true
libc = "glibc"
os = "linux"

    [[docker.download]]
    sha256 = "dd6ff72df1edfd61ae55feaa4aadb88634161f0aa06dbaaf291d1be594099ff3"
    url = "https://download.docker.com/linux/static/stable/x86_64/docker-20.10.11.tgz"
[[docker]]
arch = "aarch64"
git-tree-sha1 = "a4e4e60ef7942cdb26487a05bd6800be98bf1c61"
lazy = true
libc = "glibc"
os = "linux"

    [[docker.download]]
    sha256 = "87a4219c54552797ffd38790b72832372a90eceb7c8e451c36a682093d57dae6"
    url = "https://download.docker.com/linux/static/stable/aarch64/docker-20.10.11.tgz"

[[docker-rootless-extras]]
arch = "x86_64"
git-tree-sha1 = "f544afd3702e23df0819a378c6bdb2bbf6f6b828"
lazy = true
libc = "glibc"
os = "linux"

    [[docker-rootless-extras.download]]
    sha256 = "595f3bcd61aaa01ece8f967e4f6c5cd1fe05c3de9736bf595b0a7c99ba7b9eaf"
    url = "https://download.docker.com/linux/static/stable/x86_64/docker-rootless-extras-20.10.11.tgz"
[[docker-rootless-extras]]
arch = "aarch64"
git-tree-sha1 = "0320f85d281583e7f48e5b5a550ceaab287c4c5d"
lazy = true
libc = "glibc"
os = "linux"

    [[docker-rootless-extras.download]]
    sha256 = "753d79fe76fa3dedbba7d49fad48e2b9cb222b38c72d2b2040a36bff006ea9e7"
    url = "https://download.docker.com/linux/static/stable/aarch64/docker-rootless-extras-20.10.11.tgz"
