[[buildkite-agent-rootfs]]
arch = "x86_64"
git-tree-sha1 = "858d126789a134b09d97f890d79e4dc04fffd6b0"
libc = "glibc"
os = "linux"
lazy = true

    [[buildkite-agent-rootfs.download]]
    sha256 = "eb4dca4876b3751ab3900a3674765142041418025a0d2f7c2b0248d87c3e7032"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v4.13/agent_linux.x86_64.tar.gz"

[[buildkite-agent-rootfs]]
arch = "aarch64"
git-tree-sha1 = "c1eceb419d2a6974300b718059a35a01956315aa"
libc = "glibc"
os = "linux"
lazy = true

    [[buildkite-agent-rootfs.download]]
    sha256 = "4943e6952cf6c0870ad0f33f3fada386b8a728e0ee7f2120e3da88c98e2560e3"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v5.11/agent_linux.aarch64.tar.gz"

[[buildkite-agent-rootfs]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4eada831fb72837b4408194ab4222f61ea393e39"
libc = "glibc"
os = "linux"
lazy = true

    [[buildkite-agent-rootfs.download]]
    sha256 = "fe664e1441b96843678de0e58c4f5f1d3d5c0eb8cd59d7ba4c8ddc0ec448ff8e"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v5.11/agent_linux.armv7l.tar.gz"

[[buildkite-agent-rootfs]]
arch = "powerpc64le"
git-tree-sha1 = "438305c26992cc821426d1f8f151dbb69445a7e0"
libc = "glibc"
os = "linux"
lazy = true

    [[buildkite-agent-rootfs.download]]
    sha256 = "6b4e47ccd0abe814b47429ab35826a6dc2b46c3692813c8637cc25e2b4c02ac2"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v5.14/agent_linux.ppc64le.tar.gz"

[[docker]]
arch = "x86_64"
git-tree-sha1 = "b4df8f522b707a6bc56dc11c07c0a1d1b8703ac3"
libc = "glibc"
os = "linux"
lazy = true

    [[docker.download]]
    sha256 = "dd6ff72df1edfd61ae55feaa4aadb88634161f0aa06dbaaf291d1be594099ff3"
    url = "https://download.docker.com/linux/static/stable/x86_64/docker-20.10.11.tgz"

[[docker]]
arch = "aarch64"
git-tree-sha1 = "a4e4e60ef7942cdb26487a05bd6800be98bf1c61"
libc = "glibc"
os = "linux"
lazy = true

    [[docker.download]]
    sha256 = "87a4219c54552797ffd38790b72832372a90eceb7c8e451c36a682093d57dae6"
    url = "https://download.docker.com/linux/static/stable/aarch64/docker-20.10.11.tgz"

[[docker-rootless-extras]]
arch = "x86_64"
git-tree-sha1 = "f544afd3702e23df0819a378c6bdb2bbf6f6b820"
libc = "glibc"
os = "linux"
lazy = true

    [[docker-rootless-extras.download]]
    sha256 = "595f3bcd61aaa01ece8f967e4f6c5cd1fe05c3de9736bf595b0a7c99ba7b9eaf"
    url = "https://download.docker.com/linux/static/stable/x86_64/docker-rootless-extras-20.10.11.tgz"

[[docker-rootless-extras]]
arch = "aarch64"
git-tree-sha1 = "0320f85d281583e7f48e5b5a550ceaab287c4c5d"
libc = "glibc"
os = "linux"
lazy = true

    [[docker-rootless-extras.download]]
    sha256 = "753d79fe76fa3dedbba7d49fad48e2b9cb222b38c72d2b2040a36bff006ea9e7"
    url = "https://download.docker.com/linux/static/stable/aarch64/docker-rootless-extras-20.10.11.tgz"

[[buildkite-agent]]
arch = "x86_64"
git-tree-sha1 = "1dea9726c236c94998d86fb7ebedcc788a9e8537"
os = "macos"
lazy = true

    [[buildkite-agent.download]]
    sha256 = "19f108798308a98dcdddb750faea1f8fa8dc832501fa46757ca4b462b9eb58a0"
    url = "https://github.com/buildkite/agent/releases/download/v3.33.3/buildkite-agent-darwin-amd64-3.33.3.tar.gz"

[[buildkite-agent]]
arch = "aarch64"
git-tree-sha1 = "864c85c068102fe7819f77da78caf57aa77ce37d"
os = "macos"
lazy = true

    [[buildkite-agent.download]]
    sha256 = "1f7ad047f264750fb4b98e9cb7a439a768496358b544641da904913800d035c8"
    url = "https://github.com/buildkite/agent/releases/download/v3.33.3/buildkite-agent-darwin-arm64-3.33.3.tar.gz"

