[[buildkite-agent]]
arch = "x86_64"
git-tree-sha1 = "15118bd950d8f0116bd165134d7e04f8bac96904"
os = "macos"

    [[buildkite-agent.download]]
    sha256 = "cd0e9da824edea14889447865c0dd6bf90651d712915904ddbd572f49c49eb25"
    url = "https://github.com/buildkite/agent/releases/download/v3.127.2/buildkite-agent-darwin-amd64-3.127.2.tar.gz"
[[buildkite-agent]]
arch = "aarch64"
git-tree-sha1 = "cac286e10919e58bc8382d3f92051617b5fd6b55"
os = "macos"

    [[buildkite-agent.download]]
    sha256 = "8763418091d622f69b7196487d500aa040b78b77bc5ba0ccbad973a5cdb991e9"
    url = "https://github.com/buildkite/agent/releases/download/v3.127.2/buildkite-agent-darwin-arm64-3.127.2.tar.gz"
[[buildkite-agent]]
arch = "x86_64"
git-tree-sha1 = "6358f724a7114f842a2c1507e7e1cc11402e0f12"
libc = "glibc"
os = "linux"

    [[buildkite-agent.download]]
    sha256 = "6a83b8016dabb2d12b2c8651eea5edb8a98dce2700f8888019fc2bc7c5ae13d8"
    url = "https://github.com/buildkite/agent/releases/download/v3.127.2/buildkite-agent-linux-amd64-3.127.2.tar.gz"
[[buildkite-agent]]
arch = "aarch64"
git-tree-sha1 = "3fa87cc61ae8277e1dffe348eed6d9055c84edd0"
libc = "glibc"
os = "linux"

    [[buildkite-agent.download]]
    sha256 = "5bc021b783a3be06f0204d19f1374beab079ccd90b0e145958263fa8b6ae069e"
    url = "https://github.com/buildkite/agent/releases/download/v3.127.2/buildkite-agent-linux-arm64-3.127.2.tar.gz"
[[buildkite-agent]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "39250a334adcab0d6e521a62bd2ba1163c71062d"
libc = "glibc"
os = "linux"

    [[buildkite-agent.download]]
    sha256 = "cd279df3a638c0179be58fb920f7f8aba739047defba02e931cb7350171e025c"
    url = "https://github.com/buildkite/agent/releases/download/v3.127.2/buildkite-agent-linux-armhf-3.127.2.tar.gz"
[[buildkite-agent]]
arch = "powerpc64le"
git-tree-sha1 = "b4cf67cb26f30b94efc4019448c3c6d5926cadd7"
libc = "glibc"
os = "linux"

    [[buildkite-agent.download]]
    sha256 = "6bff4efcbbde09aa1e5f2e1d83d9fbab4eeffaf1cda278108f381062f61f2f04"
    url = "https://github.com/buildkite/agent/releases/download/v3.127.2/buildkite-agent-linux-ppc64le-3.127.2.tar.gz"

[[buildkite-agent-rootfs]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a89c3544c9a4a9cd75b6d76e2d6537334d5e754f"
libc = "glibc"
os = "linux"

    [[buildkite-agent-rootfs.download]]
    sha256 = "369ae6da1e9ad8aed16aac41125c75bd12f8119542ed1d6d0a44b236d016b3db"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v8.4/agent_linux.armv7l.tar.gz"
[[buildkite-agent-rootfs]]
arch = "powerpc64le"
git-tree-sha1 = "1c512b24331ad8aa7b51a5c9defd651830770ee8"
libc = "glibc"
os = "linux"

    [[buildkite-agent-rootfs.download]]
    sha256 = "e46215bdf18b741af24ee4d7ce94083f323617012a32e17be3d81b299711c925"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v8.4/agent_linux.ppc64le.tar.gz"
[[buildkite-agent-rootfs]]
arch = "x86_64"
git-tree-sha1 = "d3bac85f30061dd4b7a42402c74ff89fccd19c4e"
libc = "glibc"
os = "linux"

    [[buildkite-agent-rootfs.download]]
    sha256 = "3b901634d80b8bfafa02294eb7a0a96bdccdd119a2d881c7f3c0875ec4f35cdb"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v8.4/agent_linux.x86_64.tar.gz"
[[buildkite-agent-rootfs]]
arch = "aarch64"
git-tree-sha1 = "9ee615d703522322f7dcece77caba25c39f592eb"
libc = "glibc"
os = "linux"

    [[buildkite-agent-rootfs.download]]
    sha256 = "bd67c283931d86e285709aed4ce15b1fb193e9825eedd3004f273ec81d6009c6"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v8.4/agent_linux.aarch64.tar.gz"

[[docker]]
arch = "x86_64"
git-tree-sha1 = "b4df8f522b707a6bc56dc11c07c0a1d1b8703ac3"
lazy = true
libc = "glibc"
os = "linux"

    [[docker.download]]
    sha256 = "dd6ff72df1edfd61ae55feaa4aadb88634161f0aa06dbaaf291d1be594099ff3"
    url = "https://download.docker.com/linux/static/stable/x86_64/docker-20.10.11.tgz"
[[docker]]
arch = "aarch64"
git-tree-sha1 = "a4e4e60ef7942cdb26487a05bd6800be98bf1c61"
lazy = true
libc = "glibc"
os = "linux"

    [[docker.download]]
    sha256 = "87a4219c54552797ffd38790b72832372a90eceb7c8e451c36a682093d57dae6"
    url = "https://download.docker.com/linux/static/stable/aarch64/docker-20.10.11.tgz"

[[docker-rootless-extras]]
arch = "x86_64"
git-tree-sha1 = "f544afd3702e23df0819a378c6bdb2bbf6f6b828"
lazy = true
libc = "glibc"
os = "linux"

    [[docker-rootless-extras.download]]
    sha256 = "595f3bcd61aaa01ece8f967e4f6c5cd1fe05c3de9736bf595b0a7c99ba7b9eaf"
    url = "https://download.docker.com/linux/static/stable/x86_64/docker-rootless-extras-20.10.11.tgz"
[[docker-rootless-extras]]
arch = "aarch64"
git-tree-sha1 = "0320f85d281583e7f48e5b5a550ceaab287c4c5d"
lazy = true
libc = "glibc"
os = "linux"

    [[docker-rootless-extras.download]]
    sha256 = "753d79fe76fa3dedbba7d49fad48e2b9cb222b38c72d2b2040a36bff006ea9e7"
    url = "https://download.docker.com/linux/static/stable/aarch64/docker-rootless-extras-20.10.11.tgz"
