[[buildkite-agent]]
arch = "x86_64"
git-tree-sha1 = "8b22243fed9a314b766d80458491cf73b005766f"
os = "macos"

    [[buildkite-agent.download]]
    sha256 = "54899b5c0c43d4a6ee25065d443c6ba1faea0022bfc86ab52e7a737817217fc8"
    url = "https://github.com/buildkite/agent/releases/download/v3.103.0/buildkite-agent-darwin-amd64-3.103.0.tar.gz"
[[buildkite-agent]]
arch = "aarch64"
git-tree-sha1 = "90baa190031a8cb72887ecad2a4126855670fb92"
os = "macos"

    [[buildkite-agent.download]]
    sha256 = "d9ad60f24700874089b205871b7e04ae7322e73422752b784914c35bbbd8a7d3"
    url = "https://github.com/buildkite/agent/releases/download/v3.103.0/buildkite-agent-darwin-arm64-3.103.0.tar.gz"

[[buildkite-agent-rootfs]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ba792f2335e891af0ba163d2e2601f37568b1f8c"
libc = "glibc"
os = "linux"

    [[buildkite-agent-rootfs.download]]
    sha256 = "4ebf84350af0993249f6a27901d4733110ce01d094939a49133be74baa5228a9"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v7.11/agent_linux.armv7l.tar.gz"
[[buildkite-agent-rootfs]]
arch = "powerpc64le"
git-tree-sha1 = "0cc2badb7bc68915d2a410af97c71386faf11c54"
libc = "glibc"
os = "linux"

    [[buildkite-agent-rootfs.download]]
    sha256 = "b1b723651758b37e5668c21b3f496d2ba45eed3fb447ede32baf00a0c5f35f21"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v7.11/agent_linux.ppc64le.tar.gz"
[[buildkite-agent-rootfs]]
arch = "x86_64"
git-tree-sha1 = "6e38f17af54975f714f6a9f423728a2bcc32d46d"
libc = "glibc"
os = "linux"

    [[buildkite-agent-rootfs.download]]
    sha256 = "a997900c621e2a9e8d85420d69400ca1f251281281be56856439277f80d8e9cc"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v7.11/agent_linux.x86_64.tar.gz"
[[buildkite-agent-rootfs]]
arch = "aarch64"
git-tree-sha1 = "bcc3ae68211f64407e27217216438a2a004d60f6"
libc = "glibc"
os = "linux"

    [[buildkite-agent-rootfs.download]]
    sha256 = "1ade33912504d21f65c7f71478665055ffd6e867cdb5c93fbb145c6ca805afff"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v7.11/agent_linux.aarch64.tar.gz"

[[docker]]
arch = "x86_64"
git-tree-sha1 = "b4df8f522b707a6bc56dc11c07c0a1d1b8703ac3"
lazy = true
libc = "glibc"
os = "linux"

    [[docker.download]]
    sha256 = "dd6ff72df1edfd61ae55feaa4aadb88634161f0aa06dbaaf291d1be594099ff3"
    url = "https://download.docker.com/linux/static/stable/x86_64/docker-20.10.11.tgz"
[[docker]]
arch = "aarch64"
git-tree-sha1 = "a4e4e60ef7942cdb26487a05bd6800be98bf1c61"
lazy = true
libc = "glibc"
os = "linux"

    [[docker.download]]
    sha256 = "87a4219c54552797ffd38790b72832372a90eceb7c8e451c36a682093d57dae6"
    url = "https://download.docker.com/linux/static/stable/aarch64/docker-20.10.11.tgz"

[[docker-rootless-extras]]
arch = "x86_64"
git-tree-sha1 = "f544afd3702e23df0819a378c6bdb2bbf6f6b828"
lazy = true
libc = "glibc"
os = "linux"

    [[docker-rootless-extras.download]]
    sha256 = "595f3bcd61aaa01ece8f967e4f6c5cd1fe05c3de9736bf595b0a7c99ba7b9eaf"
    url = "https://download.docker.com/linux/static/stable/x86_64/docker-rootless-extras-20.10.11.tgz"
[[docker-rootless-extras]]
arch = "aarch64"
git-tree-sha1 = "0320f85d281583e7f48e5b5a550ceaab287c4c5d"
lazy = true
libc = "glibc"
os = "linux"

    [[docker-rootless-extras.download]]
    sha256 = "753d79fe76fa3dedbba7d49fad48e2b9cb222b38c72d2b2040a36bff006ea9e7"
    url = "https://download.docker.com/linux/static/stable/aarch64/docker-rootless-extras-20.10.11.tgz"
