[[buildkite-agent-rootfs]]
arch = "x86_64"
git-tree-sha1 = "0f26b5cf04e937bcbbdc6586a47cb6e1a70955b7"
libc = "glibc"
os = "linux"
lazy = true

    [[buildkite-agent-rootfs.download]]
    sha256 = "daf8e7e40e455a250fe1f2c983daab64fa07629b3a0289932db58224e38facd7"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v1/buildkite-agent.tar.gz"
